### ISSUE TITLE
Update gh-pages branch

### ISSUE THREAD

**Issue by Krinkle** [cbrandolino/local-audio-visualizer#2]
Hi @cbrandolino,

I found a copy of your tutorial at <https://www.tutorialspoint.com/html5/audio_demo.htm>. The source pointed me to your GitHub, which I see has a different look and style. However, I noticed that your original demo at <http://cbrandolino.github.io/local-audio-visualizer/> has stopped working due to `ReferenceError: webkitAudioContext is not defined`.

It appears this was already fixed in master some years ago, but the gh-pages branch for GitHub Pages is missing this commit.

Could you apply it there as well? Note that GitHub now allows Pages sites also to point directly to your master branch, which might be useful for this repo.

Thanks!

**Comment by cbrandolino** [comment]
Hey @Krinkle - thanks for the heads up!

The tutorial wasn't mine, looks like tutorialspoint just downloaded and zipped the repo without notice nor credit lol :)

At any rate, fixed now!
